version: "3.7"

services:
  mongo:
    container_name: todo-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - todo-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  todo-mongo-data:
